# Generated by Django 5.0 on 2024-01-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='site_id',
            field=models.CharField(default='aaa', max_length=50),
            preserve_default=False,
        ),
    ]
